#!/usr/bin/env python3
"""Generate ignored Google OAuth configuration for desktop or oauth-tagged builds.

Use --client-file PATH or LEDGESYNC_GOOGLE_DESKTOP_CLIENT_JSON, never credentials
in command-line arguments. Only Google installed Desktop client JSON is accepted;
user-token fields, alternate endpoints, duplicate keys and unsafe files fail.
This is a build input, not a Google authorization or token import operation.
"""
from __future__ import annotations
import argparse
import ctypes
import json
import os
from pathlib import Path
import re
import stat
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'internal/connections/oauth_client_generated.go'
ENVIRONMENT_KEY = 'LEDGESYNC_GOOGLE_DESKTOP_CLIENT_JSON'
MAX_BYTES = 32 * 1024
MARKER = b'// Code generated by tools/configure_oauth_client.py; DO NOT EDIT.\n'
FAILURE = 'Google Desktop OAuth build configuration failed; provide a valid client file or repository secret.'


class ConfigurationError(ValueError):
    def __init__(self):
        super().__init__(FAILURE)


def require(value):
    if not value:
        raise ConfigurationError()


def unique_object(pairs):
    value = {}
    for key, item in pairs:
        require(key not in value)
        value[key] = item
    return value


def reject_constant(_):
    raise ConfigurationError()


def validate_client(data: bytes) -> str:
    require(type(data) is bytes and 0 < len(data) <= MAX_BYTES)
    try:
        document = json.loads(data.decode('utf-8'), object_pairs_hook=unique_object,
                              parse_constant=reject_constant)
    except (ValueError, UnicodeError, RecursionError):
        raise ConfigurationError() from None
    require(isinstance(document, dict) and set(document) == {'installed'})
    installed = document['installed']
    required = {'client_id', 'client_secret', 'auth_uri', 'token_uri', 'redirect_uris'}
    optional = {'project_id', 'auth_provider_x509_cert_url'}
    require(isinstance(installed, dict) and required <= set(installed) <= required | optional)
    for key, value in installed.items():
        if key != 'redirect_uris':
            require(isinstance(value, str) and len(value) <= 1024
                    and all(33 <= ord(character) <= 126 for character in value))
    require(re.fullmatch(r'[A-Za-z0-9_-]{1,240}\.apps\.googleusercontent\.com', installed['client_id']))
    require(0 < len(installed['client_secret']) <= 1024)
    require(installed['auth_uri'] in ('https://accounts.google.com/o/oauth2/auth',
                                      'https://accounts.google.com/o/oauth2/v2/auth'))
    require(installed['token_uri'] == 'https://oauth2.googleapis.com/token')
    require(installed.get('auth_provider_x509_cert_url', '') in ('', 'https://www.googleapis.com/oauth2/v1/certs'))
    redirects = installed['redirect_uris']
    require(isinstance(redirects, list) and 1 <= len(redirects) <= 8)
    require(all(isinstance(value, str) and value in {
        'http://localhost', 'http://localhost/', 'http://127.0.0.1',
        'http://127.0.0.1/', 'http://[::1]', 'http://[::1]/'} for value in redirects))
    # The runtime parser requires only these fields. Do not copy development
    # project identifiers or unused certificate metadata into distributed code.
    packaged = {'installed': {key: installed[key] for key in required}}
    return json.dumps(packaged, ensure_ascii=True, separators=(',', ':'), sort_keys=True)


def regular_node(info):
    require(stat.S_ISREG(info.st_mode) and not stat.S_ISLNK(info.st_mode)
            and not getattr(info, 'st_file_attributes', 0) & 0x400)  # Windows reparse point


def checked_parents(path: Path):
    for parent in path.absolute().parents:
        info = parent.lstat()
        require(stat.S_ISDIR(info.st_mode) and not stat.S_ISLNK(info.st_mode)
                and not getattr(info, 'st_file_attributes', 0) & 0x400)


def read_client_file(path: Path) -> bytes:
    checked_parents(path)
    before = path.lstat()
    regular_node(before)
    require(0 < before.st_size <= MAX_BYTES)
    descriptor = os.open(path, os.O_RDONLY | getattr(os, 'O_NOFOLLOW', 0)
                         | getattr(os, 'O_NONBLOCK', 0) | getattr(os, 'O_BINARY', 0))
    with os.fdopen(descriptor, 'rb') as stream:
        opened = os.fstat(stream.fileno())
        regular_node(opened)
        require(os.path.samestat(before, opened))
        data = stream.read(MAX_BYTES + 1)
        after = os.fstat(stream.fileno())
        require(os.path.samestat(opened, after) and opened.st_size == after.st_size
                and opened.st_mtime_ns == after.st_mtime_ns and len(data) == opened.st_size)
    return data


def restrict_file(path: Path):
    os.chmod(path, 0o600)
    if os.name != 'nt':
        require(stat.S_IMODE(path.stat().st_mode) == 0o600)
        return
    # chmod cannot express a private NTFS ACL. Apply an owner-only protected DACL
    # before writing any client bytes, using OS APIs without shell commands.
    from ctypes import wintypes
    advapi = ctypes.WinDLL('advapi32.dll', use_last_error=True, winmode=0x800)
    kernel = ctypes.WinDLL('kernel32.dll', use_last_error=True, winmode=0x800)
    convert = advapi.ConvertStringSecurityDescriptorToSecurityDescriptorW
    convert.argtypes = [wintypes.LPCWSTR, wintypes.DWORD, ctypes.POINTER(ctypes.c_void_p), ctypes.c_void_p]
    convert.restype = wintypes.BOOL
    apply = advapi.SetFileSecurityW
    apply.argtypes = [wintypes.LPCWSTR, wintypes.DWORD, ctypes.c_void_p]
    apply.restype = wintypes.BOOL
    kernel.LocalFree.argtypes = [ctypes.c_void_p]
    kernel.LocalFree.restype = ctypes.c_void_p
    descriptor = ctypes.c_void_p()
    require(convert('D:P(A;;FA;;;OW)', 1, ctypes.byref(descriptor), None))
    try:
        require(apply(str(path), 0x00000004 | 0x80000000, descriptor))
    finally:
        kernel.LocalFree(descriptor)


def generate(data: bytes, destination: Path = OUTPUT):
    client = validate_client(data)
    checked_parents(destination)
    require(destination.name == OUTPUT.name and not os.path.lexists(destination))
    # JSON quoting yields a valid Go interpreted string for this ASCII schema;
    # no -ldflags/-X, environment value, or command argument reaches the compiler.
    content = MARKER + ('//go:build desktop || oauth\n\npackage connections\n\n'
        'func init() {\n\tbundledClientJSON = ' + json.dumps(client) + '\n}\n').encode('ascii')
    descriptor, temporary = tempfile.mkstemp(prefix='.oauth-client-', suffix='.tmp', dir=destination.parent)
    path = Path(temporary)
    try:
        with os.fdopen(descriptor, 'wb') as stream:
            restrict_file(path)
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        checked_parents(destination)
        # Hard-link publication is atomic and refuses any pre-existing target.
        # Same-directory links preserve 0600 / the protected Windows DACL.
        os.link(path, destination, follow_symlinks=False)
    finally:
        path.unlink(missing_ok=True)


def clean(destination: Path = OUTPUT):
    checked_parents(destination)
    if not os.path.lexists(destination):
        return
    require(destination.name == OUTPUT.name)
    regular_node(destination.lstat())
    with destination.open('rb') as source:
        require(source.read(len(MARKER)) == MARKER)
    destination.unlink()


def main(argv=None):
    class SafeParser(argparse.ArgumentParser):
        def error(self, message):
            raise ConfigurationError()
    parser = SafeParser(description=__doc__)
    parser.add_argument('--client-file', type=Path)
    parser.add_argument('--clean', action='store_true', help='Remove only this helper\'s generated source')
    try:
        args = parser.parse_args(argv)
        if args.clean:
            require(args.client_file is None)
            clean()
            return 0
        value = os.environ.pop(ENVIRONMENT_KEY, '')
        require(not (args.client_file is not None and value))
        data = read_client_file(args.client_file) if args.client_file is not None else value.encode('utf-8')
        generate(data)
    except (ValueError, OSError, UnicodeError, RecursionError):
        print(FAILURE, file=sys.stderr)
        return 1
    print('Google Desktop OAuth client configured for this desktop build.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
